### ISSUE TITLE
Theme can not be removed Firefox 96

### ISSUE THREAD

**Issue by asaidac** [dave1b/firefoxTheme#1]
Is there a way to remove this theme?
Thanks

**Comment by dave1b** [comment]
type in _about:addons_ in the search bar
delete as shown in the screenshot
![grafik](https://user-images.githubusercontent.com/57140925/149343520-03c43d1e-d884-458f-b6be-26d435bc7e3f.png)

**Comment by asaidac** [comment]
The only available optionis = Manage

**Comment by asaidac** [comment]
Please disregard - I was able to remove in Firefox safe mode
